server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #服务端主机ip地址
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #自己就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    #设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #单机版
      defaultZone: http://eureka7001.com:7001/eureka  #相互守望，互相注册