server:
  port: 8002
spring:
  application:
    name: cloud-payment-server #实例名 集群时保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包路径
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.springcloud.entities  #所有Entity别名所在包
eureka:
  client:
    register-with-eureka: true  #向注册中心注册自己，默认为true
    #是否从eureka抓取已有的注册信息，默认为true，单节点无所谓，多节点集群必须设置为treu，才能配置ribbon使用负载均衡
    fetch-registry: true
    #告诉他去哪注册和发现
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002  #修改服务实例主机名称的显示
    prefer-ip-address: true  #显示服务实例的真实ip地址和端口