server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh             #路由的ID，没有固定的规则，但要求唯一，建议配合服务名
         # uri: http://localhost:8001    #匹配提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVER  #通过微服务名动态路由，lb代表负载均衡
          predicates:                     #一组匹配规则，只有满足所有匹配规则才会匹配该路由
            - Path=/payment/get/**      #断言，路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVER
          predicates:
            - Path=/payment/lb/**
#            - After=2020-07-26T17:00:31.766+08:00[Asia/Shanghai]
#            - Cookie=username,hl
      discovery:
        locator:
          enabled: true #开启动态路由
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service