server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
#消费者要去访问的微服务名称（成功注册进nacos的服务提供者,restTemplate访问
service-url:
  nacos-user-service: http://nacos-payment-provider/
